Corrige herança entre CursoUFG e InstanciaAdm
ES-INF-UFG-2016-2/Sempre-UFG pull request #132
Opened 2016-11-01 18:15 UTC by clebersa

Esse pullrequest tem como objetivo adicionar herança entre CursoUFG e InstanciaAdm, e colocar o atributo nome da classe InstanciaAdm dentro dos padrões do projeto. Isso era um erro de implementação e tornou-se uma pendência para a tarefa [Implementar testes funcionais RNF-AutentUsu, contemplando testes para a condição de primeiro acesso do usuário Egresso](https://trello.com/c/qBqhYs2K/288-implementar-testes-funcionais-rnf-autentusu-contemplando-testes-para-a-condicao-de-primeiro-acesso-do-usuario-egresso) no Trello.

2016-11-04 16:26 UTC, gustavosotnas commented
@clebersa Você errou ao criar o Pull Request para o `master`. Mudei a *base branch* para **`develop`**, mas preste atenção da próxima vez que criar um Pull Request quanto à esse parâmetro.

2016-11-04 16:38 UTC, gustavomdsantos submitted a review, later dismissed

2016-11-04 18:22 UTC, gustavosotnas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Controlar a configuração do software do Grupo 1](https://trello.com/c/pCFnt4gP/356-controlar-a-configuracao-do-software-do-grupo-1)

2016-11-29 03:32 UTC, gustavomdsantos requested changes
@clebersa Não posso aprovar este Pull Request como ele está. A classe CursoUFG na branch `develop` foi modificada para tipo **`Serializable`** antes de você modificar esta classe. Faça as devidas alterações no código para que o código esteja atualizado com a branch `develop` e compilando.

2016-12-05 22:42 UTC, closed without merging

2016-12-16 13:55 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar testes funcionais RNF-AutentUsu, contemplando testes para a condição de primeiro acesso do usuário Egresso](https://trello.com/c/qBqhYs2K/288-implementar-testes-funcionais-rnf-autentusu-contemplando-testes-para-a-condicao-de-primeiro-acesso-do-usuario-egresso)