Adiciona nacionalidade do egresso
ES-INF-UFG-2016-2/Sempre-UFG pull request #133
Opened 2016-11-02 01:01 UTC by clebersa

Este pull request tem por objetivo adicionar o atributo nacionalidade do tipo LocalizaoGeografica à classe Egresso, conforme especificado no documento de requisitos (Figura 1. Visão do egresso na UFG).

2016-11-04 18:22 UTC, gustavosotnas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Controlar a configuração do software do Grupo 1](https://trello.com/c/pCFnt4gP/356-controlar-a-configuracao-do-software-do-grupo-1)

2016-11-29 03:39 UTC, gustavomdsantos requested changes
Como dito no PR #132 / #212, existe um conflito sério que deve ser resolvido ao fazer *merge* da branch `develop` para esta.

2016-12-05 23:44 UTC, gustavomdsantos approved these changes

2016-12-05 23:44 UTC, merged

2016-12-16 13:55 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar testes funcionais RNF-AutentUsu, contemplando testes para a condição de primeiro acesso do usuário Egresso](https://trello.com/c/qBqhYs2K/288-implementar-testes-funcionais-rnf-autentusu-contemplando-testes-para-a-condicao-de-primeiro-acesso-do-usuario-egresso)