Iplementa testes funcionais do requsito RNF-AutentUsu
ES-INF-UFG-2016-2/Sempre-UFG pull request #134
Opened 2016-11-02 01:36 UTC by clebersa

Esse pull request tem por objetivo adicionar os testes funcionais do requisito RNF-AutentUsu. Além disso, os testes para a autenticação do primeiro acesso do egresso também estão sendo adicionados nesse pull request.

2016-11-02 02:29 UTC, clebersa commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar testes funcionais RNF-AutentUsu, contemplando testes para a condição de primeiro acesso do usuário Egresso](https://trello.com/c/qBqhYs2K/288-implementar-testes-funcionais-rnf-autentusu-contemplando-testes-para-a-condicao-de-primeiro-acesso-do-usuario-egresso)

2016-11-04 18:22 UTC, gustavosotnas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Controlar a configuração do software do Grupo 1](https://trello.com/c/pCFnt4gP/356-controlar-a-configuracao-do-software-do-grupo-1)

2016-11-29 03:49 UTC, gustavomdsantos requested changes
O mesmo problema das PRs #132 e #133 acontece aqui também. **Conflitos** com relação ao tipo da classe, que devem ser resolvidos:

![diff develop-> G1-ImplementarTestesFun-RNF-AutentUsu](http://imgh.us/Captura_de_tela_de_2016-11-29_01:23:02.png)
*Diff comparando a classe `CursoUFG` que está nesta branch com a que está na `develop`*

2016-12-06 13:57 UTC, clebersa commented
@gustavosotnas, eu fiz as mudanças. O branch está pronto.

2016-12-06 16:34 UTC, gustavomdsantos approved these changes

2016-12-06 16:35 UTC, merged