G3 refazer rd ens medio egres
ES-INF-UFG-2016-2/Sempre-UFG pull request #159
Opened 2016-11-19 04:32 UTC by RenanOfugi

Testes de RD usando JUnit finalizado

2016-11-28 22:22 UTC, Yuri-M-Dias requested changes
Problemas de compilação com o pacote, não está atualizado para a versão do Master.

2016-12-05 12:59 UTC, RenanOfugi commented
@Yuri-M-Dias Problema corrigido

2016-12-05 13:00 UTC, RenanOfugi commented
@Yuri-M-Dias Problema corrigido

2016-12-05 21:27 UTC, Yuri-M-Dias commented
@RenanOfugi não faz sentido a sua 'correção'. Você não está usando o pacote sempreufg que está como a estrutura oficial do proejto, e isso pode levar a complicações depois.

2016-12-09 18:04 UTC, RenanOfugi commented
@Yuri-M-Dias atualizei a branch com a atual estrutura do develop e remanejei as classes pros seus pacotes específicos.

2016-12-12 15:47 UTC, Yuri-M-Dias commented
@RenanOfugi os testes estão falhando nessa PR, é bom dar uma olhada

2016-12-19 01:11 UTC, merged