Projeta o requisito para salvar os resultados de consulta
ES-INF-UFG-2016-2/Sempre-UFG pull request #162
Opened 2016-11-20 17:23 UTC by kaiqueorange

Projeto do requisito RF-SalvaPlaniEgres para salvar os resultados da consulta em arquivo tipo planilha.

2016-11-20 17:25 UTC, kaiqueorange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Projetar RF-SalvaPlaniEgres](https://trello.com/c/yxGBSJz9/140-projetar-rf-salvaplaniegres)

2016-11-21 01:27 UTC, leonardofreitass requested changes
Os diagramas estão nos lugares corretos, mas por favor, retire o atalho HTML para o draw.io para a aprovação deste PR.

2016-11-22 02:49 UTC, kaiqueorange commented
Remove arquivos com extenção html submetidos erroneamente, e adiciona os editaveis em xml

2016-11-27 21:31 UTC, leonardofreitass requested changes
@kaiqueorange Há um leve erro na nomeação dos arquvios, umespaço em branco onde deveria ser um '-'. Após este ajuste o PR será aprovado, pois no demais, os arquivos e encontram de acordo com o plano de GCO.

2016-12-18 19:42 UTC, leonardofreitass approved these changes

2016-12-18 19:59 UTC, merged