Ajusta e melhora os layout de tela e storyboard conforme solicitado pelo professor.
ES-INF-UFG-2016-2/Sempre-UFG pull request #174
Opened 2016-11-22 19:33 UTC by kaiqueorange

2016-11-22 19:35 UTC, kaiqueorange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar storyboard para RNF-MantPapel](https://trello.com/c/GtyZJXth/331-implementar-storyboard-para-rnf-mantpapel)

2016-12-12 21:52 UTC, leonardofreitass requested changes
O nome do arquivo possui um espaço incorreto, favor modificar para aprovação do PR.

2016-12-16 13:38 UTC, kaiqueorange commented
![](https://github.trello.services/images/mini-trello-icon.png) [Definir leiautes de tela e storyboard para RNF-MantPapel](https://trello.com/c/ajIaFAKs/325-definir-leiautes-de-tela-e-storyboard-para-rnf-mantpapel)

2016-12-18 19:39 UTC, leonardo-freitas-1995 commented
PR será transferido para Branch Final por falta da adequação pedida.

2016-12-18 19:52 UTC, leonardofreitass submitted a review, later dismissed

2016-12-18 20:04 UTC, merged