G2-Implementar-Testes-Funcionais-RNF-ConsulLog
ES-INF-UFG-2016-2/Sempre-UFG pull request #200
Opened 2016-12-02 02:37 UTC by kleudson

2016-12-02 02:43 UTC, kleudson commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar testes funcionais RNF-ConsulLog](https://trello.com/c/8wSdeFRP/279-implementar-testes-funcionais-rnf-consullog)

2016-12-05 21:55 UTC, leonardofreitass requested changes
A coneão está sendo feita manualmente via JDBC, e a mesma deve ser feita utilizando o framework Hibernate.

2016-12-05 23:51 UTC, leonardo-freitas-1995 commented
@kleudson 
Os arquivos de configuração do Hibernate foram enviados para sua branch por merge, dê um git pull para atualizar localmente.
Exemplo de como fazer as anotações nas classes pode ser encontrada [aqui](https://github.com/ES-INF-UFG-2016-2/Sempre-UFG/blob/G1-RF-ExecCons/src/main/java/br/ufg/inf/sempreufg/modelo/Entidade.java)
Um bom tutorial sobre hibernate pode ser encontrado [aqui](https://www.tutorialspoint.com/hibernate/)

2016-12-18 19:35 UTC, leonardofreitass approved these changes

2016-12-18 19:44 UTC, merged