Finalização da tarefa Projetar RNF-ConfigAtualEgres
ES-INF-UFG-2016-2/Sempre-UFG pull request #223
Opened 2016-12-07 21:37 UTC by LucasFerreiraRodrigue

2016-12-07 21:38 UTC, LucasFerreiraRodrigue commented
![](https://github.trello.services/images/mini-trello-icon.png) [Projetar RNF-ConfigAtualEgres](https://trello.com/c/MMB5PboU/127-projetar-rnf-configatualegres)

2016-12-12 21:13 UTC, leonardofreitass approved these changes

2016-12-12 21:14 UTC, leonardofreitass requested changes
É preciso adequar a nomeação do .xml, após isso o PR será aprovado.

2016-12-18 19:33 UTC, leonardofreitass approved these changes

2016-12-18 19:50 UTC, merged