Implementa Storyboard RNF-ContAcesPapel
ES-INF-UFG-2016-2/Sempre-UFG pull request #224
Opened 2016-12-08 15:34 UTC by pauloXtr3m

2016-12-08 15:35 UTC, pauloXtr3m commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar storyboard para RNF-ContrAcesPapel](https://trello.com/c/BXgh7pVv/323-implementar-storyboard-para-rnf-contracespapel)

2016-12-12 20:35 UTC, Yuri-M-Dias requested changes
Isso é um template, não é a implementação do Storyboard. Olhe também como o Igor fez nos includes para colocar com o padrão que está o projeto.

2016-12-16 00:21 UTC, Yuri-M-Dias commented
@pauloXtr3m pode aceitar a pull request desse jeito? Só lembrando que só posso aceitar elas até amanhã.

2016-12-16 21:27 UTC, Yuri-M-Dias approved these changes

2016-12-16 21:27 UTC, merged