Adiciona Diagramas RNF Consultar Log
ES-INF-UFG-2016-2/Sempre-UFG pull request #228
Opened 2016-12-11 14:16 UTC by jeancarlosjc

Adiciona diagramas de sequencia, classes e atividades referente ao consultar log.

2016-12-11 14:35 UTC, jeancarlosjc commented
![](https://github.trello.services/images/mini-trello-icon.png) [Projetar RNF-ConsulLog](https://trello.com/c/95t0FS2O/282-projetar-rnf-consullog)

2016-12-12 20:54 UTC, leonardofreitass requested changes
Existe um pequeno erro na nomeação dos arquivos: deveria ser usado _ como separador entre tipo do artefato e seu identificador.

2016-12-14 15:40 UTC, jeancarlosjc commented
@leonardo-freitas-1995 realizei a alteração nos nomes dos arquivos, obrigado por me notificar.

2016-12-18 19:33 UTC, leonardofreitass approved these changes

2016-12-18 19:47 UTC, merged