G1 implementar storyboard para rf importegresperiod
ES-INF-UFG-2016-2/Sempre-UFG pull request #236
Opened 2016-12-12 21:49 UTC by carvalhobm

2016-12-12 21:49 UTC, carvalhobm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar storyboard para RF-ImportEgresPeriod](https://trello.com/c/KVwewAKQ/224-implementar-storyboard-para-rf-importegresperiod)

2016-12-16 05:45 UTC, gustavomdsantos requested changes
@carvalhobm Existem conflitos em arquivos na sua branch com relação à branch **`develop`**. Tentei fazer o merge eu mesmo mas a classe `EgressoService` e o `WEB-INF/web.xml` estão totalmente diferentes.

Faça um **merge** da branch **`develop`** para a sua branch corrigindo esses conflitos, dando preferência em deixar a implementação já existente em **`develop`** porque ela está um pouco mais estável. Recomendo a ferramenta [SmartGit](http://www.syntevo.com/smartgit) para isso, é um cliente Git para Windows, Linux e Mac OS X.

Você tem até o final do dia de hoje para solucionar este problema (16/12/2016).

2016-12-16 12:36 UTC, carvalhobm commented
@gustavosotnas Merge realizado, porem as classes EgressoDAO e EgressoaDAOInterface geraram o problema de build do travis, classes estas que não realizei alteração o git apenas fez o update delas na minha branch.

2016-12-16 14:09 UTC, carvalhobm commented
Ja encontrei o problema que deu nos nomes das classes no merge e fiz a correção.

2016-12-19 11:02 UTC, gustavomdsantos approved these changes

2016-12-19 11:03 UTC, merged