G1-RF-ExecCons
ES-INF-UFG-2016-2/Sempre-UFG pull request #248
Opened 2016-12-15 16:03 UTC by daniel-oliveiravas

2016-12-16 06:21 UTC, gustavomdsantos requested changes
@daniel-oliveiravas para que é este Pull Request? Não há coisa alguma descrevendo para que serve, e se já posso avaliar ou você ainda não terminou o trabalho. Me parece que está incompleto. Há conflitos com a branch `develop`. E o Travis CI está avisando de falhas, você precisa corrigir isso até o final do dia de hoje (16/12/2016).

2016-12-16 22:53 UTC, daniel-oliveiravas commented
@gustavosotnas Não entendi seus questionamentos. Esse pull request é com relação à implementação da minha atividade, que é "Implementar RF-ExecCons". Com relação à implementação, ela foi validada com o Product Owner e está tudo de acordo.

2016-12-16 23:24 UTC, daniel-oliveiravas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar RF-ExecCons](https://trello.com/c/Z4ndFcB0/137-implementar-rf-execcons)

2016-12-20 18:04 UTC, gustavomdsantos approved these changes

2016-12-20 18:07 UTC, merged