G1 rnf mant papel
ES-INF-UFG-2016-2/Sempre-UFG pull request #251
Opened 2016-12-15 22:48 UTC by BrunoVieiraAndrade

2016-12-15 22:50 UTC, BrunoVieiraAndrade commented
![](https://github.trello.services/images/mini-trello-icon.png) [Projetar RNF-MantPapel](https://trello.com/c/aNYw8yY7/324-projetar-rnf-mantpapel)

2016-12-16 06:27 UTC, gustavomdsantos requested changes
@BrunoVieiraAndrade seus diagramas estão corretos mas existem dois problemas:
 * Os diagramas estão na pasta errada. A pasta `ARQ` não existe mais, agora ela é `arq`. Observe que na sua branch ficou duas pastas de diagramas, e isso não se espera de acontecer. Mova-os para a pasta correta até o final do dia de hoje (16/12/2016).
 * Estão faltando os arquivos `.xml` do [draw.io](http://draw.io) (suponho que tenha sido nessa ferramenta que você tenha feito esses diagramas). Adicione-os na mesma pasta corrigidos até o final do dia de hoje (16/12/2016).

2016-12-16 19:16 UTC, BrunoVieiraAndrade commented
@gustavosotnas Eu realizei as alterações e inserções que você pediu. Movi os arquivos para a pasta correta,  adicionei os arquivos XML que estavam faltando, e como a pasta "ARQ" possui arquivos que não foram desenvolvidos por mim, eu preferi não deletá-la sem ter autorização para tal.

2016-12-20 18:11 UTC, gustavomdsantos approved these changes
@BrunoVieiraAndrade agora está correto. Quanto à questão dos diagramas feitos por outras pessoas na pasta errada, isso já foi resolvido na branch `develop` semana passada, e essa resolução foi aplicada na sua branch com um *merge* da `develop` para esta branch.

2016-12-20 18:11 UTC, merged