G1 - Implementação dos testes para o RD-GestSis
ES-INF-UFG-2016-2/Sempre-UFG pull request #71
Opened 2016-10-25 00:09 UTC by daniel-oliveiravas

Os testes só irão passar quando forem executados em um máquina com um banco de dados em que o DDL esteja configurado.

2016-10-25 00:10 UTC, daniel-oliveiravas commented
@gustavosotnas @Yuri-M-Dias @leonardo-freitas-1995 Temos que estudar como será a estratégia para que os testes sobre requisitos de dados sejam executados corretamente.

2016-10-25 00:54 UTC, Yuri-M-Dias commented
@daniel-oliveiravas Eu comecei a estudar e dei a ideia pro pessoal no Trello pra usar o Flyway pra executar migrations. Não seria tão difícil de mudar a estrutura atual para integrar o Flyway, e obrigaríamos os DDLs futuros a seguirem um padrão em que PRECISARÃO rodar (também é a melhor forma de rodar eles no Travis), mas não deu ainda pra implementar isso direito... Eu atualizei o Travis pra rodar o mariadb E o postgres, mas falta executar os SQLs ainda pra testar nos dois: https://github.com/ES-INF-UFG-2016-2/Sempre-UFG/tree/G3-adiciona-postgres-travis

2016-10-25 01:50 UTC, gustavosotnas commented
@Yuri-M-Dias, se não deu para implementar o Flyway, vamos fazer algum script que faz o Travis instalar o MariaDB e o PostgreSQL e executar algo do tipo `psql *.sql || mysql *.sql`?

2016-10-25 10:17 UTC, Yuri-M-Dias commented
@gustavosotnas Essa é a outra possibilidade, mas essa abordagem é difícil de controlar depois de um tempo. E não seria um só script, seriam vários...imagine termos que organizar cada script pela ordem correta que devem ser executados para não ter nenhum conflito... Não é só "colocar o flyway no projeto", teríamos que mudar a forma como os DDLs/DMLs estão sendo feitos, e corrigir os antigos.

2016-10-25 10:32 UTC, gustavosotnas commented
@Yuri-M-Dias não acho que seja tão difícil, imaginei um Shell Script que executa os scripts `.sql` na ordem definida por um arquivo de configuração nosso, que poderia ser em formato de texto simples ou estruturado, como **YAML**, que pode ser editado facilmente pelo próprio autor do seus DDLs / DMLs, mais ou menos desse jeito:

**1 - Texto simples**
```
db/ddl/ijkl.sql
db/ddl/mnopq.sql
db/ddl/rstuvw.sql
db/dml/xyz.sql
...
```
**2 - YAML**
```yaml
ddl:
 - ijkl.sql
 - mnopq.sql
 - rstuvw.sql
 - xyz.sql
dml:
 - xyz.sql
...
```

2016-10-25 10:36 UTC, gustavosotnas commented
@Yuri-M-Dias já viu isso aqui também?

https://docs.travis-ci.com/user/database-setup/#PostgreSQL

2016-10-25 10:53 UTC, Yuri-M-Dias commented
@gustavosotnas foi exatamente isso que eu fiz no branch que eu testei, gustavo. O problema é que nós teríamos que reordernar os SQLs, não importa a abordagem que tentarmos, seja por shell ou por migrations. Criarmos o nosso próprio pode funcionar a princípio, mas não é exatamente manutenível... Mas se for pra fazer uma coisa nesse estilo, eu fiz uma coisa parecida no SempreUFG do semestre passado, dá pra reusar os scripts de criação do banco de boa:
https://github.com/Yuri-M-Dias/SempreUFG/blob/master/postgres.sh
https://github.com/Yuri-M-Dias/SempreUFG/blob/master/create-user-and-db.sql
Disso seria "só" pegar os arquivos e ler eles. Podemos arrumar uma coisa assim temporária pra fazer as pull requests passarem, por exemplo essa e a do Rafael do meu grupo #50

2016-10-25 11:15 UTC, gustavosotnas commented
@Yuri-M-Dias então eu não entendi qual a dificuldade de fazer manutenção numa integração como essa. Qual seria o processo?

2016-10-31 22:52 UTC, daniel-oliveiravas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implementar testes RD-GestSis](https://trello.com/c/pDJA2JSQ/61-implementar-testes-rd-gestsis)

2016-10-31 22:56 UTC, gustavosotnas commented
O DDL do @wylkerxpz para o RD-GestSis está com problema. Ele deve estar rodando com os testes.

2016-11-01 11:32 UTC, daniel-oliveiravas commented
@gustavosotnas Passei as correções necessárias para ele no cartão do trello.

2016-11-04 18:05 UTC, gustavosotnas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Controlar a configuração do software do Grupo 1](https://trello.com/c/pCFnt4gP/356-controlar-a-configuracao-do-software-do-grupo-1)

2016-12-12 23:54 UTC, daniel-oliveiravas commented
@gustavosotnas E esse pull request ?

2016-12-13 10:13 UTC, gustavosotnas commented
@daniel-oliveiravas como o @Yuri-M-Dias publicou na **`develop`** o PR #217 ontem, vou revisar seu PR no quesito de os testes passarem no Travis CI do projeto depois de você atualizar esta branch com a **`develop`** (inclusive resolvendo o conflito no arquivo `pom.xml` pelo fato desta branch ser antiga).

2016-12-16 06:50 UTC, gustavosotnas commented
@daniel-oliveiravas arrume esse build por favor.

2016-12-16 06:51 UTC, gustavomdsantos requested changes
@daniel-oliveiravas arrume esse build por favor. O código é antigo e tem muitas diferenças com o da branch **`develop`**.

2016-12-16 23:22 UTC, daniel-oliveiravas commented
@gustavosotnas Não é possível implementar essa atividade à tempo. A demora na configuração do ambiente de integração contínua e a construção do script final do DDL  foi muito alta. Dessa forma, eu teria que implementar a atividade inteira novamente, de forma à adaptá-la ao novo DDL. Então, provavelmente este pull request ficará aberto.

2016-12-20 17:57 UTC, gustavosotnas commented
Este PR não tem condições de estar na branch `develop`, mas irá para a branch `final`.

2016-12-20 18:50 UTC, merged